apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdbgui-deployment
  namespace: sample-namespace
  labels:
    app: gdbgui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdbgui
  template:
    metadata:
      labels:
        app: gdbgui
    spec:
      containers:
      - name: gdbgui
        image: tomj0101/gdbgui:lasted
        ports:
        - containerPort: 5555